version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: your-postgres-username
      POSTGRES_PASSWORD: your-postgres-password
      POSTGRES_DB: your-postgres-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
